
// export const data = [
//     {
//         key: 1,
//         channel: 'PDF',
//         documentName: "And Design System Guide",
//         group: "Receipts",
//         status: "Received",
//         dateModified: "2021-02-05",
//         type: "Prior",
//         adress: '/localhost',
//     },
//     {
//         key: 2,
//         channel: 'SMS',
//         documentName: "Laboris Ant Design nisi ult aliquip",
//         group: "Fintech",
//         status: "Printed",
//         dateModified: "2021/02/02",
//         type: "Non-prior",
//         adress: '/localhost/c$',
//     },
//     {
//         key: 3,
//         channel: 'PDF',
//         documentName: "And Design System Guide v.2",
//         group: "Users",
//         status: "Sorted",
//         dateModified: "2021/02/02",
//         type: "Regist",
//         adress: '/localhost/etc/fstab',
//     },
//     {
//         key: 4,
//         channel: 'PDF',
//         documentName: "Et adipiscing vitae amet mauris eget vel Ant Design",
//         group: "RRHH",
//         status: "Received",
//         dateModified: "2021/02/02",
//         type: "Regist",
//         adress: '/c:/WWS/clock.avi',
//     },
//     {
//         key: 5,
//         channel: 'John Brown',
//         documentName: "Document",
//         group: "Receipts",
//         status: "Received",
//         dateModified: "2021/02/02",
//         type: "Regist",
//         adress: 'New York No. 1 Lake Park',
//     },
//     {
//         key: 6,
//         channel: 'Jim Green',
//         documentName: "Document",
//         group: "Receipts",
//         status: "Received",
//         dateModified: "2021/02/02",
//         type: "Prior",
//         adress: 'London No. 1 Lake Park',
//     },
//     {
//         key: 7,
//         channel: 'Joe Black',
//         documentName: "Document",
//         group: "Receipts",
//         status: "Received",
//         dateModified: "2021/02/02",
//         type: "Prior",
//         adress: 'Sidney No. 1 Lake Park',
//     },
// ];